import { useEffect, useRef } from "react";
import gsap from "gsap";
import CarbonList from "../../components/carbon/CarbonList";
import CarbonSummary from "../../components/carbon/CarbonSummary";

const CarbonTracking = () => {
  const containerRef = useRef(null);
  const headerRef = useRef(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.fromTo(
        headerRef.current.children,
        { opacity: 0, y: 15 },
        {
          opacity: 1,
          y: 0,
          duration: 0.5,
          stagger: 0.08,
          ease: "power2.out",
        }
      );
    }, containerRef);

    return () => ctx.revert();
  }, []);

  return (
    <div
      ref={containerRef}
      className="min-h-screen bg-[#FFFBF5] font-['Montserrat',sans-serif] text-[#422D0B] p-4 sm:p-8 space-y-8 max-w-7xl mx-auto"
    >
      {/* Page Header */}
      <header
        ref={headerRef}
        className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-[#E8DDCB] pb-6"
      >
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
            <span className="text-[10px] font-extrabold uppercase tracking-widest text-[#967A53]">
              Personal Sustainability Dashboard
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-[#422D0B] tracking-tight">
            My Carbon Impact
          </h1>
          <p className="text-xs sm:text-sm font-medium text-[#967A53]">
            Track the environmental impact and CO₂ offsets generated by your waste contributions.
          </p>
        </div>

        {/* User Impact Context Pill */}
        <div className="flex items-center gap-3 bg-white border border-[#E8DDCB] px-4 py-2.5 rounded-2xl shadow-2xs self-start md:self-auto">
          <div className="w-8 h-8 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-center text-emerald-600 font-black text-xs">
            🌿
          </div>
          <div>
            <span className="block text-[10px] font-extrabold uppercase tracking-wider text-[#967A53]">
              Eco Contributor
            </span>
            <span className="text-xs font-black text-[#422D0B]">
              Verified Impact
            </span>
          </div>
        </div>
      </header>

      {/* Primary Summary Metrics */}
      <section className="space-y-3">
        <div className="flex items-center justify-between">
          <h2 className="text-xs font-extrabold uppercase tracking-widest text-[#967A53]">
            Lifetime Impact Summary
          </h2>
        </div>
        <CarbonSummary />
      </section>

      {/* Section Divider */}
      <hr className="border-[#E8DDCB]" />

      {/* Carbon Records List */}
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="space-y-0.5">
            <h2 className="text-lg font-black text-[#422D0B] tracking-tight">
              Carbon Records
            </h2>
            <p className="text-xs text-[#967A53]">
              History of offset records calculated for your processed contributions
            </p>
          </div>
        </div>

        <div className="bg-white border border-[#E8DDCB] rounded-3xl p-4 sm:p-6 shadow-2xs">
          <CarbonList />
        </div>
      </section>
    </div>
  );
};

export default CarbonTracking;