import { useEffect, useState } from "react";
import CarbonList from "../../components/carbon/CarbonList";
import CarbonSummary from "../../components/carbon/CarbonSummary";
import CarbonImpactForm from "../../components/carbon/CarbonImpactForm";
import api from "../../services/api";

const CarbonTracking = () => {
    const [receivedWaste, setReceivedWaste] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    const fetchReceivedWaste = async () => {
        try {
            setLoading(true);
            setError("");

            const response = await api.get("/waste/received");

            setReceivedWaste(response.data?.wasteBatches || []);
        } catch (err) {
            setError(
                err.response?.data?.message ||
                "Failed to fetch received waste."
            );
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchReceivedWaste();
    }, []);

    return (
        <div className="min-h-screen bg-[#0C1C18] p-4 sm:p-7 max-w-7xl mx-auto font-['Plus_Jakarta_Sans',sans-serif] text-[#F4F6F0] space-y-8 relative selection:bg-[#2D6B4E] selection:text-white">
            {/* Background Decorative Ambient Glows */}
            <div className="fixed inset-0 overflow-hidden pointer-events-none">
                <div className="absolute -top-40 -left-40 w-96 h-96 bg-[#2D6B4E]/10 rounded-full blur-3xl" />
                <div className="absolute top-1/2 -right-40 w-96 h-96 bg-[#143B36]/30 rounded-full blur-3xl" />
            </div>

            <div className="relative z-10 space-y-8">
                {/* Header */}
                <div className="border-b border-[#143B36] pb-6">
                    <span className="text-[10px] font-extrabold uppercase tracking-widest text-[#8EA097]">
                        Facility Environmental Analytics
                    </span>

                    <h1 className="text-2xl sm:text-3xl font-black tracking-tight mt-1 text-[#F4F6F0]">
                        Carbon Impact Tracking
                    </h1>

                    <p className="text-sm text-[#8EA097] mt-1">
                        Record processing activities and measure the carbon impact
                        generated by your facility.
                    </p>
                </div>

                {/* Summary */}
                <section className="space-y-3">
                    <h2 className="text-xs font-extrabold uppercase tracking-widest text-[#8EA097]">
                        Facility Impact Summary
                    </h2>

                    <CarbonSummary />
                </section>

                {/* Received Waste */}
                <section className="space-y-4">
                    <div>
                        <h2 className="text-lg font-black tracking-tight text-[#F4F6F0]">
                            Pending Carbon Processing
                        </h2>

                        <p className="text-xs text-[#8EA097] mt-1">
                            Select a processing method for waste received at your
                            facility.
                        </p>
                    </div>

                    {loading && (
                        <div className="bg-[#143B36] border border-[#235349] rounded-2xl p-6 text-sm text-[#8EA097] flex items-center gap-3 shadow-[0px_4px_24px_rgba(10,28,24,0.4)]">
                            <div className="w-5 h-5 border-2 border-[#235349] border-t-[#73A892] rounded-full animate-spin" />
                            <span>Loading received waste...</span>
                        </div>
                    )}

                    {error && (
                        <div className="bg-[#143B36] border border-red-500/30 text-red-200 rounded-2xl p-4 text-xs font-bold shadow-[0px_4px_24px_rgba(10,28,24,0.4)]">
                            {error}
                        </div>
                    )}

                    {!loading && !error && receivedWaste.length === 0 && (
                        <div className="bg-[#143B36] border border-dashed border-[#235349] rounded-2xl p-8 text-center shadow-[0px_4px_24px_rgba(10,28,24,0.4)]">
                            <div className="w-12 h-12 bg-[#0C1C18] border border-[#235349] text-[#73A892] rounded-full flex items-center justify-center mx-auto text-xl mb-3">
                                🌱
                            </div>

                            <h3 className="text-sm font-black text-[#F4F6F0]">
                                No Waste Awaiting Processing
                            </h3>

                            <p className="text-xs text-[#8EA097] mt-1 max-w-sm mx-auto">
                                Waste batches will appear here after they are
                                delivered and marked as received.
                            </p>
                        </div>
                    )}

                    {!loading && receivedWaste.length > 0 && (
                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
                            {receivedWaste.map((wasteBatch) => (
                                <CarbonImpactForm
                                    key={wasteBatch._id}
                                    wasteBatch={wasteBatch}
                                    facilityId={wasteBatch.facility}
                                    onSuccess={() => {
                                        fetchReceivedWaste();
                                        window.location.reload();
                                    }}
                                />
                            ))}
                        </div>
                    )}
                </section>

                <hr className="border-[#143B36]" />

                {/* Carbon Records */}
                <section className="space-y-4">
                    <div>
                        <h2 className="text-lg font-black tracking-tight text-[#F4F6F0]">
                            Carbon Records
                        </h2>

                        <p className="text-xs text-[#8EA097] mt-1">
                            History of carbon impact generated through your
                            facility's processing activities.
                        </p>
                    </div>

                    <div className="bg-[#143B36] border border-[#235349] rounded-2xl p-4 sm:p-6 shadow-[0px_4px_24px_rgba(10,28,24,0.4)]">
                        <CarbonList />
                    </div>
                </section>
            </div>
        </div>
    );
};

export default CarbonTracking;