import { useEffect, useState } from "react";
import CarbonList from "../../components/carbon/CarbonList";
import CarbonSummary from "../../components/carbon/CarbonSummary";
import CarbonImpactForm from "../../components/carbon/CarbonImpactForm";
import api from "../../services/api";

const CarbonTracking = () => {
    const [receivedWaste, setReceivedWaste] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    const fetchReceivedWaste = async () => {
        try {
            setLoading(true);
            setError("");

            const response = await api.get("/waste/received");

            setReceivedWaste(response.data?.wasteBatches || []);
        } catch (err) {
            setError(
                err.response?.data?.message ||
                "Failed to fetch received waste."
            );
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchReceivedWaste();
    }, []);

    return (
        <div className="min-h-screen bg-[#F4F6F0] p-4 sm:p-7 max-w-7xl mx-auto font-['Plus_Jakarta_Sans',sans-serif] text-[#162925] space-y-8">

            {/* Header */}
            <div className="border-b border-[#E1E6DE] pb-6">
                <span className="text-[10px] font-extrabold uppercase tracking-widest text-[#6B7D76]">
                    Facility Environmental Analytics
                </span>

                <h1 className="text-2xl sm:text-3xl font-black tracking-tight mt-1">
                    Carbon Impact Tracking
                </h1>

                <p className="text-sm text-[#6B7D76] mt-1">
                    Record processing activities and measure the carbon impact
                    generated by your facility.
                </p>
            </div>

            {/* Summary */}
            <section className="space-y-3">
                <h2 className="text-xs font-extrabold uppercase tracking-widest text-[#6B7D76]">
                    Facility Impact Summary
                </h2>

                <CarbonSummary />
            </section>

            {/* Received Waste */}
            <section className="space-y-4">
                <div>
                    <h2 className="text-lg font-black tracking-tight">
                        Pending Carbon Processing
                    </h2>

                    <p className="text-xs text-[#6B7D76] mt-1">
                        Select a processing method for waste received at your
                        facility.
                    </p>
                </div>

                {loading && (
                    <div className="bg-white border border-[#E1E6DE] rounded-2xl p-6 text-sm text-[#6B7D76]">
                        Loading received waste...
                    </div>
                )}

                {error && (
                    <div className="bg-[#FDF2F2] border border-[#F8D7DA] text-[#A94442] rounded-2xl p-4 text-xs font-bold">
                        {error}
                    </div>
                )}

                {!loading && !error && receivedWaste.length === 0 && (
                    <div className="bg-white border border-dashed border-[#D5DED8] rounded-2xl p-8 text-center">
                        <div className="text-2xl mb-2">🌱</div>

                        <h3 className="text-sm font-black">
                            No Waste Awaiting Processing
                        </h3>

                        <p className="text-xs text-[#6B7D76] mt-1">
                            Waste batches will appear here after they are
                            delivered and marked as received.
                        </p>
                    </div>
                )}

                {!loading && receivedWaste.length > 0 && (
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
                        {receivedWaste.map((wasteBatch) => (
                            <CarbonImpactForm
                                key={wasteBatch._id}
                                wasteBatch={wasteBatch}
                                facilityId={wasteBatch.facility}
                                onSuccess={() => {
                                    fetchReceivedWaste();
                                    window.location.reload();
                                }}
                            />
                        ))}
                    </div>
                )}
            </section>

            <hr className="border-[#E1E6DE]" />

            {/* Carbon Records */}
            <section className="space-y-4">
                <div>
                    <h2 className="text-lg font-black tracking-tight">
                        Carbon Records
                    </h2>

                    <p className="text-xs text-[#6B7D76] mt-1">
                        History of carbon impact generated through your
                        facility's processing activities.
                    </p>
                </div>

                <div className="bg-white border border-[#E1E6DE] rounded-2xl p-4 sm:p-6 shadow-sm">
                    <CarbonList />
                </div>
            </section>
        </div>
    );
};

export default CarbonTracking;